<a href="https://colab.research.google.com/github/Kolexx/Economy_of_the_United_Kingdom-DAta-project/blob/main/Untitled4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from bs4 import BeautifulSoup
import requests

In [4]:
url = 'https://en.m.wikipedia.org/wiki/Economy_of_the_United_Kingdom'
page = requests.get(url)
soup = BeautifulSoup(page.text, 'html')

In [ ]:
soup.find('table', class_ = 'wikitable')

In [5]:
table = soup.find_all('table')[1]

In [6]:
sector_titles = table.find_all('th')
print(sector_titles)

[<th>Sector</th>, <th>GVA <sup class="reference" id="cite_ref-BB2023IAFig1_148-0"><a href="#cite_note-BB2023IAFig1-148">[136]</a></sup></th>, <th>% of GVA <sup class="reference" id="cite_ref-BB2023IAFig1_148-1"><a href="#cite_note-BB2023IAFig1-148">[136]</a></sup></th>, <th>Employee compensation <sup class="reference" id="cite_ref-BB2023IAFig3_149-0"><a href="#cite_note-BB2023IAFig3-149">[137]</a></sup></th>, <th>% of employee compensation <sup class="reference" id="cite_ref-BB2023IAFig3_149-1"><a href="#cite_note-BB2023IAFig3-149">[137]</a></sup>
</th>]

In [7]:
sector_table_titles = [title.text.strip() for title in sector_titles]
print(sector_table_titles)

['Sector', 'GVA [136]', '% of GVA [136]', 'Employee compensation [137]', '% of employee compensation [137]']

In [8]:
import pandas as pd
df = pd.DataFrame(columns= sector_table_titles)
df

Empty DataFrame
Columns: [Sector, GVA [136], % of GVA [136], Employee compensation [137], % of employee compensation [137]]
Index: []

In [9]:
sector_roles = table.find_all('tr')

In [15]:
for row in sector_roles[1:]:
    row_data = row.find_all('td')
    ind_row_data = [role.text.strip() for role in row_data]

    length = len(df)
    df.loc[length] = ind_row_data

In [29]:
df

,Sector,GVA [136],% of GVA [136],Employee compensation [137],% of employee compensation [137]
0,,£M,%,£M,%
1,Agriculture,16206,0.8,4887,0.4
2,Production,259522,12.7,143992,12.5
3,Construction,119920,5.9,53142,4.6
4,Distribution,335709,16.4,235682,20.4
5,Information,131244,6.4,87369,7.6
6,Financial,185434,9.1,87738,7.6
7,Real Estate,266136,13.0,18011,1.6
8,Professional,264877,12.9,176238,15.2
9,Government (including health and education),405455,19.8,313594,27.1
10,Other Services,62133,3.0,35499,3.1

In [17]:
table2 = soup.find_all('table')[2]
Tourism_titles = table2.find_all('th')
print(Tourism_titles)

[<th>Rank
</th>, <th>Market
</th>, <th>Spend
</th>, <th>Visitors
</th>]

In [18]:
Tourism_table_titles = [title.text.strip() for title in Tourism_titles]
print(Tourism_table_titles)

['Rank', 'Market', 'Spend', 'Visitors']

In [19]:
Tf = pd.DataFrame(columns= Tourism_table_titles)
Tf

Empty DataFrame
Columns: [Rank, Market, Spend, Visitors]
Index: []

In [20]:
Tourism_roles = table2.find_all('tr')

In [30]:
for row in Tourism_roles[1:]:
    row_data1 = row.find_all('td')
    ind_row_data1 = [role.text.strip() for role in row_data1]

    length = len(Tf)
    Tf.loc[length] = ind_row_data1

    # print(ind_row_data1)

In [31]:
Tf

  Rank          Market          Spend    Visitors
0    1  European Union  £9.33 billion  22,580,591
1    2   United States  £4.18 billion   4,498,753
2    3           China  £1.71 billion     883,072
3    4       Australia  £1.17 billion   1,063,404
4    5           India   £752 million     692,082
5    6          Canada   £734 million     874,060
6    7    Saudi Arabia   £627 million     220,780
7    8     Switzerland   £569 million     925,727
8    9          Norway   £436 million     647,460
9   10           Japan   £369 million     388,839

In [33]:
table3 = soup.find_all('table')[3]
Exchange_titles = table3.find_all('th')
print(Exchange_titles)

[<th>Year </th>, <th>£/US$ </th>, <th>US$/£ </th>, <th><a href="/wiki/Coefficient_of_variation" title="Coefficient of variation">C.var</a></th>, <th>  </th>, <th>£/XEU </th>, <th>XEU/£</th>, <th>C.var
</th>, <th>Year </th>, <th>£/US$ </th>, <th>US$/£ </th>, <th>C.var</th>, <th>  </th>, <th>£/€ </th>, <th>€/£</th>, <th>C.var
</th>]

In [34]:
Exchange_table_titles = [title.text.strip() for title in Exchange_titles]
print(Exchange_table_titles)

['Year', '£/US$', 'US$/£', 'C.var', '', '£/XEU', 'XEU/£', 'C.var', 'Year', '£/US$', 'US$/£', 'C.var', '', '£/€', '€/£', 'C.var']

In [35]:
ef = pd.DataFrame(columns= Exchange_table_titles)
ef

Empty DataFrame
Columns: [Year, £/US$, US$/£, C.var, , £/XEU, XEU/£, C.var, Year, £/US$, US$/£, C.var, , £/€, €/£, C.var]
Index: []

In [36]:
exchange_roles = table3.find_all('tr')

In [57]:
# for row in exchange_roles[2:]:
#   row_data2 = row.find_all('td')
#   ind_row_data2 = [role.text.strip() for role in row_data2]

#   if ind_row_data2:  # This will check if the list is non-empty
#         length = len(ef)
#         ef.loc[length] = ind_row_data2

# Assuming ef is already defined and initialized as a DataFrame with appropriate columns
column_count = len(ef.columns)

for row in exchange_roles[2:]:
    row_data2 = row.find_all('td')
    ind_row_data2 = [role.text.strip() for role in row_data2]

    if ind_row_data2:  # Ensure it's not an empty list
        if len(ind_row_data2) == column_count:
            ef.loc[len(ef)] = ind_row_data2
        elif len(ind_row_data2) < column_count:
            # Pad the row with None or appropriate values to match the number of columns
            ind_row_data2.extend([None] * (column_count - len(ind_row_data2)))
            ef.loc[len(ef)] = ind_row_data2
        else:
            # Handle the case where there are more elements than columns (optional)
            ind_row_data2 = ind_row_data2[:column_count]
            ef.loc[len(ef)] = ind_row_data2

In [58]:
ef

,Year,£/US$,US$/£,C.var,,£/XEU,XEU/£,C.var,Year,£/US$,US$/£,C.var,,£/€,€/£,C.var
0,1990,£0.5633,$1.775,,,£0.7161,₠1.397,,None,None,None,None,None,None,None,None
1,1991,£0.5675,$1.762,,,£0.7022,₠1.424,,None,None,None,None,None,None,None,None
2,1992,£0.5699,$1.755,,,£0.7365,₠1.358,,None,None,None,None,None,None,None,None
3,1993,£0.6663,$1.501,,,£0.7795,₠1.283,,None,None,None,None,None,None,None,None
4,1994,£0.6536,$1.53,,,£0.7742,₠1.292,,None,None,None,None,None,None,None,None
5,1995,£0.6338,$1.578,,,£0.82,₠1.22,,None,None,None,None,None,None,None,None
6,1996,£0.6411,$1.56,,,£0.8029,₠1.245,,None,None,None,None,None,None,None,None
7,1997,£0.6106,$1.638,,,£0.6909,₠1.447,,None,None,None,None,None,None,None,None
8,1998,£0.6037,$1.656,,,£0.6779,₠1.475,,None,None,None,None,None,None,None,None
9,1999,£0.6185,$1.617,,,£0.6595,€1.516,,None,None,None,None,None,None,None,None
10,2000,£0.6609,$1.513,,,£0.6099,€1.64,,None,None,None,None,None,None,None,None
11,2001,£0.6943,$1.44,,,£0.6223,€1.607,,None,None,None,None,None,None,None,None
12,2002,£0.6664,$1.501,,,£0.6289,€1.59,,None,None,None,None,None,None,None,None
13,2003,£0.6123,$1.633,,,£0.6924,€1.444,,None,None,None,None,None,None,None,None
14,2004,£0.5461,$1.832,2.26%,,£0.6787,€1.474,1.92%,None,None,None,None,None,None,None,None
15,2005,£0.55,$1.82,3.47%,,£0.6842,€1.462,1.27%,None,None,None,None,None,None,None,None
16,2006,£0.5435,$1.842,3.79%,,£0.6821,€1.466,1.11%,None,None,None,None,None,None,None,None
17,2007,£0.4999,$2.001,1.97%,,£0.6848,€1.461,2.4%,None,None,None,None,None,None,None,None
18,2008,£0.5499,$1.835,,,£0.7964,€1.226,,None,None,None,None,None,None,None,None
19,2009,£0.641,$1.566,,,£0.8914,€1.123,,None,None,None,None,None,None,None,None
20,2010,£0.6474,$1.546,1.27%,,£0.8586,€1.166,3.83%,None,None,None,None,None,None,None,None
21,2011,£0.6231,$1.605,3.81%,,£0.8684,€1.151,1.286%,None,None,None,None,None,None,None,None
22,2012,£0.6310,$1.585,2.74%,,£0.8112,€1.233,0.712%,None,None,None,None,None,None,None,None
23,2013,£0.6650[234],$1.503,5.17%,,£0.8496[235],€1.177,4.54%,None,None,None,None,None,None,None,None
24,2014,£0.6320[234],$1.582,5.25%,,£0.8060[235],€1.240,5.35%,None,None,None,None,None,None,None,None
25,2015,£0.6810[234],$1.468,7.20%,,£0.7262[235],€1.377,11.04%,None,None,None,None,None,None,None,None
26,2016,£0.770[234],$1.299,,,£0.8193[236],€1.2242,,None,None,None,None,None,None,None,None
27,2017,£0.808[234],$1.238,,,£0.8766[236],€1.1414,,None,None,None,None,None,None,None,None
28,2018,£0.750[234],$1.333,,,£0.885[236],€1.1301,,None,None,None,None,None,None,None,None
29,2019,£0.748[234],$1.337,,,£0.8773[236],€1.1405,,None,None,None,None,None,None,None,None