<a href="https://colab.research.google.com/github/Kolexx/Economy_of_the_United_Kingdom-DAta-project/blob/main/Untitled4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from bs4 import BeautifulSoup
import requests

In [4]:
url = 'https://en.m.wikipedia.org/wiki/Economy_of_the_United_Kingdom'
page = requests.get(url)
soup = BeautifulSoup(page.text, 'html')

In [ ]:
soup.find('table', class_ = 'wikitable')

In [5]:
table = soup.find_all('table')[1]

In [6]:
sector_titles = table.find_all('th')
print(sector_titles)

[<th>Sector</th>, <th>GVA <sup class="reference" id="cite_ref-BB2023IAFig1_148-0"><a href="#cite_note-BB2023IAFig1-148">[136]</a></sup></th>, <th>% of GVA <sup class="reference" id="cite_ref-BB2023IAFig1_148-1"><a href="#cite_note-BB2023IAFig1-148">[136]</a></sup></th>, <th>Employee compensation <sup class="reference" id="cite_ref-BB2023IAFig3_149-0"><a href="#cite_note-BB2023IAFig3-149">[137]</a></sup></th>, <th>% of employee compensation <sup class="reference" id="cite_ref-BB2023IAFig3_149-1"><a href="#cite_note-BB2023IAFig3-149">[137]</a></sup>
</th>]

In [7]:
sector_table_titles = [title.text.strip() for title in sector_titles]
print(sector_table_titles)

['Sector', 'GVA [136]', '% of GVA [136]', 'Employee compensation [137]', '% of employee compensation [137]']

In [80]:
import pandas as pd
df = pd.DataFrame(columns= sector_table_titles)
df

Empty DataFrame
Columns: [Sector, GVA [136], % of GVA [136], Employee compensation [137], % of employee compensation [137]]
Index: []

In [9]:
sector_roles = table.find_all('tr')

In [15]:
for row in sector_roles[1:]:
    row_data = row.find_all('td')
    ind_row_data = [role.text.strip() for role in row_data]

    length = len(df)
    df.loc[length] = ind_row_data

In [29]:
df

,Sector,GVA [136],% of GVA [136],Employee compensation [137],% of employee compensation [137]
0,,£M,%,£M,%
1,Agriculture,16206,0.8,4887,0.4
2,Production,259522,12.7,143992,12.5
3,Construction,119920,5.9,53142,4.6
4,Distribution,335709,16.4,235682,20.4
5,Information,131244,6.4,87369,7.6
6,Financial,185434,9.1,87738,7.6
7,Real Estate,266136,13.0,18011,1.6
8,Professional,264877,12.9,176238,15.2
9,Government (including health and education),405455,19.8,313594,27.1
10,Other Services,62133,3.0,35499,3.1

In [17]:
table2 = soup.find_all('table')[2]
Tourism_titles = table2.find_all('th')
print(Tourism_titles)

[<th>Rank
</th>, <th>Market
</th>, <th>Spend
</th>, <th>Visitors
</th>]

In [18]:
Tourism_table_titles = [title.text.strip() for title in Tourism_titles]
print(Tourism_table_titles)

['Rank', 'Market', 'Spend', 'Visitors']

In [19]:
Tf = pd.DataFrame(columns= Tourism_table_titles)
Tf

Empty DataFrame
Columns: [Rank, Market, Spend, Visitors]
Index: []

In [20]:
Tourism_roles = table2.find_all('tr')

In [30]:
for row in Tourism_roles[1:]:
    row_data1 = row.find_all('td')
    ind_row_data1 = [role.text.strip() for role in row_data1]

    length = len(Tf)
    Tf.loc[length] = ind_row_data1

    # print(ind_row_data1)

In [31]:
Tf

  Rank          Market          Spend    Visitors
0    1  European Union  £9.33 billion  22,580,591
1    2   United States  £4.18 billion   4,498,753
2    3           China  £1.71 billion     883,072
3    4       Australia  £1.17 billion   1,063,404
4    5           India   £752 million     692,082
5    6          Canada   £734 million     874,060
6    7    Saudi Arabia   £627 million     220,780
7    8     Switzerland   £569 million     925,727
8    9          Norway   £436 million     647,460
9   10           Japan   £369 million     388,839

In [33]:
table3 = soup.find_all('table')[3]
Exchange_titles = table3.find_all('th')
print(Exchange_titles)

[<th>Year </th>, <th>£/US$ </th>, <th>US$/£ </th>, <th><a href="/wiki/Coefficient_of_variation" title="Coefficient of variation">C.var</a></th>, <th>  </th>, <th>£/XEU </th>, <th>XEU/£</th>, <th>C.var
</th>, <th>Year </th>, <th>£/US$ </th>, <th>US$/£ </th>, <th>C.var</th>, <th>  </th>, <th>£/€ </th>, <th>€/£</th>, <th>C.var
</th>]

In [34]:
Exchange_table_titles = [title.text.strip() for title in Exchange_titles]
print(Exchange_table_titles)

['Year', '£/US$', 'US$/£', 'C.var', '', '£/XEU', 'XEU/£', 'C.var', 'Year', '£/US$', 'US$/£', 'C.var', '', '£/€', '€/£', 'C.var']

In [35]:
ef = pd.DataFrame(columns= Exchange_table_titles)
ef

Empty DataFrame
Columns: [Year, £/US$, US$/£, C.var, , £/XEU, XEU/£, C.var, Year, £/US$, US$/£, C.var, , £/€, €/£, C.var]
Index: []

In [36]:
exchange_roles = table3.find_all('tr')

In [57]:
# for row in exchange_roles[2:]:
#   row_data2 = row.find_all('td')
#   ind_row_data2 = [role.text.strip() for role in row_data2]

#   if ind_row_data2:  # This will check if the list is non-empty
#         length = len(ef)
#         ef.loc[length] = ind_row_data2

# Assuming ef is already defined and initialized as a DataFrame with appropriate columns
column_count = len(ef.columns)

for row in exchange_roles[2:]:
    row_data2 = row.find_all('td')
    ind_row_data2 = [role.text.strip() for role in row_data2]

    if ind_row_data2:  # Ensure it's not an empty list
        if len(ind_row_data2) == column_count:
            ef.loc[len(ef)] = ind_row_data2
        elif len(ind_row_data2) < column_count:
            # Pad the row with None or appropriate values to match the number of columns
            ind_row_data2.extend([None] * (column_count - len(ind_row_data2)))
            ef.loc[len(ef)] = ind_row_data2
        else:
            # Handle the case where there are more elements than columns (optional)
            ind_row_data2 = ind_row_data2[:column_count]
            ef.loc[len(ef)] = ind_row_data2

In [58]:
ef

,Year,£/US$,US$/£,C.var,,£/XEU,XEU/£,C.var,Year,£/US$,US$/£,C.var,,£/€,€/£,C.var
0,1990,£0.5633,$1.775,,,£0.7161,₠1.397,,None,None,None,None,None,None,None,None
1,1991,£0.5675,$1.762,,,£0.7022,₠1.424,,None,None,None,None,None,None,None,None
2,1992,£0.5699,$1.755,,,£0.7365,₠1.358,,None,None,None,None,None,None,None,None
3,1993,£0.6663,$1.501,,,£0.7795,₠1.283,,None,None,None,None,None,None,None,None
4,1994,£0.6536,$1.53,,,£0.7742,₠1.292,,None,None,None,None,None,None,None,None
5,1995,£0.6338,$1.578,,,£0.82,₠1.22,,None,None,None,None,None,None,None,None
6,1996,£0.6411,$1.56,,,£0.8029,₠1.245,,None,None,None,None,None,None,None,None
7,1997,£0.6106,$1.638,,,£0.6909,₠1.447,,None,None,None,None,None,None,None,None
8,1998,£0.6037,$1.656,,,£0.6779,₠1.475,,None,None,None,None,None,None,None,None
9,1999,£0.6185,$1.617,,,£0.6595,€1.516,,None,None,None,None,None,None,None,None
10,2000,£0.6609,$1.513,,,£0.6099,€1.64,,None,None,None,None,None,None,None,None
11,2001,£0.6943,$1.44,,,£0.6223,€1.607,,None,None,None,None,None,None,None,None
12,2002,£0.6664,$1.501,,,£0.6289,€1.59,,None,None,None,None,None,None,None,None
13,2003,£0.6123,$1.633,,,£0.6924,€1.444,,None,None,None,None,None,None,None,None
14,2004,£0.5461,$1.832,2.26%,,£0.6787,€1.474,1.92%,None,None,None,None,None,None,None,None
15,2005,£0.55,$1.82,3.47%,,£0.6842,€1.462,1.27%,None,None,None,None,None,None,None,None
16,2006,£0.5435,$1.842,3.79%,,£0.6821,€1.466,1.11%,None,None,None,None,None,None,None,None
17,2007,£0.4999,$2.001,1.97%,,£0.6848,€1.461,2.4%,None,None,None,None,None,None,None,None
18,2008,£0.5499,$1.835,,,£0.7964,€1.226,,None,None,None,None,None,None,None,None
19,2009,£0.641,$1.566,,,£0.8914,€1.123,,None,None,None,None,None,None,None,None
20,2010,£0.6474,$1.546,1.27%,,£0.8586,€1.166,3.83%,None,None,None,None,None,None,None,None
21,2011,£0.6231,$1.605,3.81%,,£0.8684,€1.151,1.286%,None,None,None,None,None,None,None,None
22,2012,£0.6310,$1.585,2.74%,,£0.8112,€1.233,0.712%,None,None,None,None,None,None,None,None
23,2013,£0.6650[234],$1.503,5.17%,,£0.8496[235],€1.177,4.54%,None,None,None,None,None,None,None,None
24,2014,£0.6320[234],$1.582,5.25%,,£0.8060[235],€1.240,5.35%,None,None,None,None,None,None,None,None
25,2015,£0.6810[234],$1.468,7.20%,,£0.7262[235],€1.377,11.04%,None,None,None,None,None,None,None,None
26,2016,£0.770[234],$1.299,,,£0.8193[236],€1.2242,,None,None,None,None,None,None,None,None
27,2017,£0.808[234],$1.238,,,£0.8766[236],€1.1414,,None,None,None,None,None,None,None,None
28,2018,£0.750[234],$1.333,,,£0.885[236],€1.1301,,None,None,None,None,None,None,None,None
29,2019,£0.748[234],$1.337,,,£0.8773[236],€1.1405,,None,None,None,None,None,None,None,None

In [65]:
# Economy by country

table6 = soup.find_all('table')[6]
Eco_country_titles = table6.find_all('th')
print(Eco_country_titles)

[<th>Rank
</th>, <th>Country
</th>, <th>GVA per head, 2020<sup class="reference" id="cite_ref-GVA_ONS20_249-0"><a href="#cite_note-GVA_ONS20-249">[237]</a></sup>
</th>]

In [66]:
Eco_country_titles_t = [title.text.strip() for title in Eco_country_titles]
print(Eco_country_titles_t)

['Rank', 'Country', 'GVA per head, 2020[237]']

In [67]:
ec = pd.DataFrame(columns= Eco_country_titles_t)
ec

Empty DataFrame
Columns: [Rank, Country, GVA per head, 2020[237]]
Index: []

In [68]:
eco_roles = table6.find_all('tr')

In [87]:
for row in eco_roles[1:]:
    row_data = row.find_all('td')
    ind_row_data = [role.text.strip() for role in row_data]


    length = len(ec)
    ec.loc[length] = ind_row_data

<ipython-input-87-01d5ea6837c3>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ec.loc[length] = ind_row_data
<ipython-input-87-01d5ea6837c3>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ec.loc[length] = ind_row_data
<ipython-input-87-01d5ea6837c3>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ec.loc[length] = ind_row_data
<ipython-input-87-01d5ea6837c3>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ec.loc[length] = ind_row_data

In [88]:
ec

  Rank           Country GVA per head, 2020[237]
0    1           England        £32,866 ($42136)
1    2          Scotland        £29,629 ($37986)
2    3  Northern Ireland        £25,575 ($32788)
3    4             Wales        £23,882 ($30618)

In [89]:
# Economy by English region

table7 = soup.find_all('table')[7]
Eco_engR_titles = table7.find_all('th')
print(Eco_engR_titles)

[<th>Rank
</th>, <th>Region
</th>, <th>GVA per head, 2020<sup class="reference" id="cite_ref-GVA_ONS20_249-1"><a href="#cite_note-GVA_ONS20-249">[237]</a></sup>
</th>]

In [90]:
Eco_engR_titles_t= [title.text.strip() for title in Eco_engR_titles]
print(Eco_engR_titles_t)

['Rank', 'Region', 'GVA per head, 2020[237]']

In [91]:
ee = pd.DataFrame(columns= Eco_engR_titles_t)
ee

Empty DataFrame
Columns: [Rank, Region, GVA per head, 2020[237]]
Index: []

In [95]:
ect_roles = table7.find_all('tr')

for row in ect_roles[1:]:
    row_data = row.find_all('td')
    ind_row_data = [role.text.strip() for role in row_data]

    length = len(ee)
    ee.loc[length] = ind_row_data

In [96]:
ee

  Rank                    Region GVA per head, 2020[237]
0    1                    London        £55,974 ($71762)
1    2        South East England        £34,516 ($44251)
2    3           East of England        £29,176 ($37405)
3    4        North West England        £28,257 ($36227)
4    5        South West England        £28,012 ($35913)
5    6             West Midlands        £26,281 ($33694)
6    7             East Midlands        £25,956 ($33277)
7    8  Yorkshire and the Humber        £25,696 ($32944)
8    9        North East England        £23,109 ($29627)

In [98]:
# Mergers and acquisitions

table8 = soup.find_all('table')[8]
Mergers = table8.find_all('th')

merge_t = [title.text.strip() for title in Mergers]
print(merge_t)

['Rank', 'Date', 'Acquirer', 'Acquirer nation', 'Target', 'Target nation', 'Value(£\xa0billions)']

In [99]:
me = pd.DataFrame(columns= merge_t)
me

Empty DataFrame
Columns: [Rank, Date, Acquirer, Acquirer nation, Target, Target nation, Value(£ billions)]
Index: []

In [103]:
merge_roles = table8.find_all('tr')

for row in merge_roles[1:]:
    row_data = row.find_all('td')
    ind_row_data = [role.text.strip() for role in row_data]


    length = len(me)
    me.loc[length] = ind_row_data

In [104]:
me

,Rank,Date,Acquirer,Acquirer nation,Target,Target nation,Value(£ billions)
0,1,14 November 1999,Vodafone AirTouch PLC,United Kingdom,Mannesmann AG,Germany,126.95
1,2,16 September 2015,Anheuser-Busch Inbev SA/NV,Belgium,SABMiller PLC,United Kingdom,77.24
2,3,4 August 2015,Royal Dutch Shell PLC,Netherlands,BG Group PLC,United Kingdom,46.70
3,4,17 January 2000,Glaxo Wellcome PLC,United Kingdom,SmithKline Beecham PLC,United Kingdom,46.48
4,5,28 October 2004,Royal Dutch Petroleum Co,Netherlands,Shell Transport & Trading Co,United Kingdom,40.75
5,6,21 October 2016,British American Tobacco PLC,United Kingdom,Reynolds American Inc,United States,40.10
6,7,15 January 1999,Vodafone Group PLC,United Kingdom,AirTouch Communications Inc,United States,36.35
7,8,30 May 2000,France Telecom SA,France,Orange PLC,United Kingdom,31.14
8,9,8 November 1998,British Petroleum Co PLC,United Kingdom,Amoco Corp,United States,29.51
9,10,31 October 2016,GE Oil & Gas,United Kingdom,Baker Hughes Inc,United States,26.63
10,11,26 February 2009,HM Treasury,United Kingdom,Royal Bank of Scotland Group,United Kingdom,25.50

In [105]:
# Data

table9 = soup.find_all('table')[9]
data = table9.find_all('th')

data_t = [title.text.strip() for title in data]
print(data_t)

['Year', 'GDP\n(in Bil. US$PPP)', 'GDP per capita\n(in US$ PPP)', 'GDP\n(in Bil. US$ nominal)', 'GDP per capita\n(in US$ nominal)', 'GDP growth\n(real)', 'In\xadflation rate\n(in\xa0%)', 'Unem\xadploy\xadment\n(in\xa0%)', 'Govern\xadment debt\n(in\xa0% of GDP)']

In [106]:
dt = pd.DataFrame(columns= data_t)
dt

Empty DataFrame
Columns: [Year, GDP
(in Bil. US$PPP), GDP per capita
(in US$ PPP), GDP
(in Bil. US$ nominal), GDP per capita
(in US$ nominal), GDP growth
(real), In­flation rate
(in %), Unem­ploy­ment
(in %), Govern­ment debt
(in % of GDP)]
Index: []

In [107]:
data_roles = table9.find_all('tr')

for row in data_roles[1:]:
    row_data = row.find_all('td')
    ind_row_data = [role.text.strip() for role in row_data]


    length = len(dt)
    dt.loc[length] = ind_row_data

In [108]:
dt

,Year,GDP\n(in Bil. US$PPP),GDP per capita\n(in US$ PPP),GDP\n(in Bil. US$ nominal),GDP per capita\n(in US$ nominal),GDP growth\n(real),In­flation rate\n(in %),Unem­ploy­ment\n(in %),Govern­ment debt\n(in % of GDP)
0,1980,511.8,"9,085.1",603.6,"10,715.4",-2.1%,16.8%,7.1%,42.6%
1,1981,556.3,"9,870.7",587.3,"10,420.4",-0.7%,12.2%,9.7%,44.8%
2,1982,602.3,"10,699.9",558.3,"9,918.9",2.0%,8.5%,10.7%,43.1%
3,1983,652.2,"11,580.6",532.1,"9,448.7",4.2%,5.2%,11.5%,41.9%
4,1984,690.9,"12,247.2",504.2,"8,938.7",2.2%,4.4%,11.8%,42.3%
5,1985,742.1,"13,121.9",536.6,"9,488.1",4.1%,5.2%,11.4%,41.3%
6,1986,780.9,"13,776.7",654.7,"11,549.7",3.2%,3.6%,11.3%,41.3%
7,1987,843.4,"14,847.8",813.1,"14,315.0",5.4%,4.1%,10.4%,39.3%
8,1988,922.1,"16,200.4",990.2,"17,398.2",5.6%,4.6%,8.6%,37.1%
9,1989,981.6,"17,198.6","1,008.4","17,667.9",2.4%,5.2%,7.2%,32.5%
10,1990,"1,024.8","17,904.8","1,195.4","20,884.2",0.6%,7.0%,7.1%,28.5%
11,1991,"1,046.9","18,226.8","1,250.3","21,767.1",-1.2%,7.5%,8.9%,28.4%
12,1992,"1,074.1","18,653.1","1,292.1","22,438.0",0.3%,4.2%,10.0%,33.2%
13,1993,"1,126.0","19,509.9","1,157.5","20,055.8",2.4%,2.5%,10.4%,37.9%
14,1994,"1,193.4","20,624.6","1,244.0","21,499.6",3.8%,2.0%,9.5%,40.6%
15,1995,"1,248.2","21,511.1","1,346.7","23,208.7",2.4%,2.6%,8.6%,43.6%
16,1996,"1,301.9","22,383.3","1,423.0","24,464.8",2.4%,2.4%,8.1%,43.7%
17,1997,"1,389.4","23,825.5","1,559.9","26,749.9",4.9%,1.8%,7.0%,43.2%
18,1998,"1,449.3","24,785.2","1,653.5","28,277.9",3.2%,1.6%,6.3%,40.9%
19,1999,"1,513.7","25,793.8","1,686.2","28,733.2",3.0%,1.3%,6.0%,39.3%
20,2000,"1,604.8","27,253.1","1,665.3","28,279.7",3.7%,0.8%,5.5%,36.6%
21,2001,"1,675.0","28,335.4","1,644.3","27,816.7",2.1%,1.2%,5.1%,33.9%
22,2002,"1,737.2","29,262.8","1,786.9","30,099.6",2.1%,1.3%,5.2%,34.1%
23,2003,"1,825.2","30,604.8","2,059.0","34,525.0",3.0%,1.4%,5.0%,35.3%
24,2004,"1,918.3","31,998.7","2,422.9","40,415.5",2.4%,1.3%,4.8%,38.2%
25,2005,"2,029.8","33,598.5","2,547.7","42,171.2",2.6%,2.1%,4.8%,39.4%
26,2006,"2,146.5","35,288.4","2,720.9","44,731.6",2.6%,2.3%,5.4%,40.4%
27,2007,"2,254.5","36,767.2","3,107.4","50,675.5",2.3%,2.3%,5.4%,41.4%
28,2008,"2,292.3","37,077.1","2,970.0","48,039.0",-0.2%,3.6%,5.7%,49.0%
29,2009,"2,209.0","35,479.0","2,434.5","39,101.2",-4.2%,2.2%,7.6%,62.8%
30,2010,"2,283.2","36,379.2","2,493.6","39,731.6",2.1%,3.3%,7.9%,74.0%
31,2011,"2,364.6","37,363.8","2,675.8","42,281.9",1.5%,4.5%,8.1%,79.5%
32,2012,"2,453.4","38,511.1","2,719.6","42,691.2",1.5%,2.8%,8.0%,82.7%
33,2013,"2,579.2","40,232.7","2,805.1","43,757.4",1.9%,2.6%,7.6%,83.6%
34,2014,"2,686.2","41,584.0","3,088.8","47,816.0",3.0%,1.5%,6.2%,85.5%
35,2015,"2,795.1","42,928.5","2,957.2","45,418.9",2.6%,0.0%,5.4%,86.0%
36,2016,"2,928.3","44,606.1","2,733.0","41,630.5",2.3%,0.7%,4.9%,85.8%
37,2017,"3,074.4","46,553.5","2,701.3","40,903.5",2.1%,2.7%,4.4%,85.1%
38,2018,"3,199.8","48,163.7","2,904.5","43,719.0",1.7%,2.5%,4.1%,84.5%
39,2019,"3,311.5","49,575.6","2,880.4","43,121.1",1.7%,1.8%,3.8%,83.9%
40,2020,"3,040.7","45,329.1","2,758.9","41,127.4",-9.3%,0.9%,4.6%,102.6%
41,2021,"3,402.7","50,522.7","3,187.6","47,328.8",7.4%,2.6%,4.5%,95.3%
42,2022,"3,776.0","55,862.1","3,198.5","47,317.6",3.6%,9.1%,3.8%,87.0%
43,2023,"3,922.9","57,821.9","3,479.5","51,286.1",0.3%,9.0%,4.8%,79.9%
44,2024,"4,027.7","59,160.0","3,757.4","55,189.5",0.6%,3.7%,5.0%,76.7%
45,2025,"4,198.8","61,471.6","3,969.9","58,120.1",2.3%,1.8%,4.3%,73.7%
46,2026,"4,373.1","63,829.0","4,217.7","61,562.0",2.2%,2.0%,4.2%,70.6%
47,2027,"4,524.5","65,857.4","4,449.8","64,768.9",1.5%,2.0%,4.2%,68.0%